#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Bootstrap local dev environment.
################################################################################

# Import smitty.
. ci/functions.sh

git remote show upstream &> /dev/null || smitty git remote add upstream https://github.com/jumanjihouse/docker-duoauthproxy.git
