#!/bin/bash
set -e

cat > ci/vars <<EOF
  VERSION=2.4.21
  BUILD_DATE=$(date +%Y%m%dT%H%M)
  VCS_REF=${CIRCLE_SHA1:0:7}
  TAG=${VERSION}-${BUILD_DATE}-git-${VCS_REF}

  # Tag for radiusd and radclient used in test harness.
  # For local testing, override this in "environment" as described in TESTING.md.
  RADIUS_TAG=3.0.12-r2-20170514T1405-git-182695d
EOF

. ci/vars
. ci/functions

# Build the authproxy.
smitty docker build \
  --build-arg VERSION=${VERSION} \
  -t duoauthproxy-builder \
  builder/

# Remove artifacts from previous runs.
smitty rm -fr duoauthproxy.tgz || :
docker rm -f builder &> /dev/null || :

# Create a tarball of built authproxy.
smitty docker run --name builder duoauthproxy-builder bash -c "tar czf /tmp/duoauthproxy.tgz /opt/duoauthproxy"

# Copy tarball into place and build runtime image.
smitty docker cp builder:/tmp/duoauthproxy.tgz runtime/
smitty docker build \
  --build-arg CI_BUILD_URL=${CIRCLE_BUILD_URL} \
  --build-arg VCS_REF=${VCS_REF} \
  --build-arg BUILD_DATE=${BUILD_DATE} \
  --build-arg VERSION=${VERSION} \
  -t duoauthproxy \
  runtime/
