#!/bin/bash
set -e

cat > ci/vars <<EOF
  VERSION=2.6.0
  BUILD_DATE=$(date +%Y%m%dT%H%M)
  VCS_REF=${CIRCLE_SHA1:0:7}
  TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}

  # Tag for radiusd and radclient used in test harness.
  # For local testing, override this in "environment" as described in TESTING.md.
  RADIUS_TAG=3.0.13-r2-20171017T0119-git-50f537b

  export VERSION
  export BUILD_DATE
  export VCS_REF
  export RADIUS_TAG
EOF

. ci/vars
. ci/functions.sh

# Build the authproxy.
smitty docker-compose build builder

# Remove artifacts from previous runs.
smitty rm -fr duoauthproxy.tgz || :
docker rm -f builder &> /dev/null || :

# Create a tarball of built authproxy.
smitty docker run --name builder duoauthproxy-builder bash -c "tar czf /tmp/duoauthproxy.tgz /opt/duoauthproxy"

# Copy tarball into place and build runtime image.
smitty docker cp builder:/tmp/duoauthproxy.tgz runtime/
smitty docker-compose build runtime
